name: '@namnh240795/verify-branch-name-action'
description: 'Verify branch name follow a certain rule'
inputs:
  regex:
    description: 'Branch name regex'
    required: true
outputs:
  pass: # id of output
    description: 'Verify Branch Name pass or not'
runs:
  using: 'node20'
  main: 'dist/index.js'